version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pub
    directory: "/packages/taggy"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/taggy/example"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_taggy"
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: "/packages/flutter_taggy/example"
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: "/packages/taggy/native"
    schedule:
      interval: weekly
