name: taggy
description: A dart package for reading, writing and converting audio files tags.
version: 1.0.0
repository: https://github.com/DMouayad/taggy

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: ^1.81.0
  meta: ^1.9.1
  path: ^1.8.0

dev_dependencies:
  ffigen: '>=8.0.0 <9.0.0'
  lints: ^2.0.0
  test: ^1.21.0
