name: taggy
description: Provides a simple yet powerful API for reading, writing and converting audio tags (metadata).
version: 0.1.2+3
repository: https://github.com/DMouayad/taggy
homepage: https://github.com/DMouayad/taggy/tree/master/packages/taggy
issue_tracker: https://github.com/DMouayad/taggy/issues

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: ^1.82.0
  meta: ^1.9.1
  path: ^1.8.0
  uuid: ^3.0.7

dev_dependencies:
  ffigen: '>=8.0.0 <9.0.0'
  lints: ^2.1.1
  test: ^1.21.0
