[package]
name = "taggy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "1.82.*"

[dependencies]
anyhow = "1.0.75"
fake = { version = "2.8.0", features = ["derive", "time"] }
flutter_rust_bridge = "1.82.*"
lofty = "0.15.0"
rand = "0.8.5"
